language: minimal

services:
    - docker

install:
    - docker build -t abesim .

script:
    - docker run -v $PWD:/root/agent_based_epidemic_sim abesim bazel test --test_output=errors agent_based_epidemic_sim/...
